version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    pull-request-branch-name:
      prefix: "deps"
    open-pull-requests-limit: 1
    groups:
      all-updates:
        patterns:
          - ".*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    pull-request-branch-name:
      prefix: "deps"
    open-pull-requests-limit: 1
    groups:
      all-updates:
        patterns:
          - ".*"
